### ISSUE TITLE
User impersonation?

### ISSUE THREAD

**Issue by ElPistoler0** [sftpgo/sftpgo-plugin-auth#1]
Hi, LOVE sFTPGo! Thank you for making it!

Now I love it even more, as AD auth is one of my obsessions.

Does your plugin support user impersonation? Meaning that the connection thread will run as the authenticated user and respect NTFS ACLs?

Thank you!

**Comment by drakkan** [comment]
No sorry, user impersonation is not supported, I have no plan to work on it. You can use the sftpgo virtual permission.
AD authentication was also supported before, you just had to write your own custom hook/plugin. 

This plugin exists thanks to a project sponsor who agreed to make it public
