### ISSUE TITLE
User deleted after new logins

### ISSUE THREAD

**Issue by daniel8800** [sftpgo/sftpgo-plugin-auth#2]
Hello.

I'm trying to implement sftpgo 2.5.3 and the sftpgo-plugin-auth and I see the following problem:
I have created a "user1" in my AD and when it authenticates I can see the user in the admin site and I can add a group (with all the settings I want for that user in sftpgo), but... if the user logout and login again, when I go to the admin site, I see the user but without the group I've already assigned to it.
Is it a bug?

All the env var I've set are the following:

/etc/sftpgo/env.d/authenv.env

SFTPGO_PLUGIN_AUTH_LDAP_URL="ldap://192.168.110.152:389"
SFTPGO_PLUGIN_AUTH_LDAP_BASE_DN="dc=xxxlab,dc=local"
SFTPGO_PLUGIN_AUTH_LDAP_USERNAME="cn=srv_sftpgo_auth,cn=users,dc=xxxlab,dc=local"
SFTPGO_PLUGIN_AUTH_LDAP_PASSWORD="xxxxxxxxxxxxxxxxxxxxxxx"
SFTPGO_PLUGIN_AUTH_LDAP_SEARCH_QUERY="(&(objectClass=user)(sAMAccountType=805306368)(sAMAccountName=%username%))"
SFTPGO_PLUGIN_AUTH_LDAP_GROUP_ATTRIBUTES="memberOf"
SFTPGO_PLUGIN_AUTH_CACHE_TIME=60
SFTPGO_PLUGINS__0__TYPE=auth
SFTPGO_PLUGINS__0__AUTH_OPTIONS__SCOPE=5
SFTPGO_PLUGINS__0__CMD="/usr/local/bin/sftpgo-plugin-auth/sftpgo-plugin-auth"
SFTPGO_PLUGINS__0__ARGS="serve"
SFTPGO_PLUGINS__0__AUTO_MTLS=1

Thanks for all.

**Comment by drakkan** [comment]
The support policy here is the same as for SFTPGo, please don't ask for free step by step support. Thanks for understanding

**Comment by wangrui1573** [comment]
I have the same problem, which is why I gave up using sftpgo and used server-u instead

**Comment by drakkan** [comment]
> I have the same problem, which is why I gave up using sftpgo and used server-u instead

I'm sorry but if you want to use SFTPGo for free (or any other free software without support) you must be ready to understand and fix issues yourself. Thanks for understandig and good luck with your project
