### ISSUE TITLE
WeDAV slows down

### ISSUE THREAD

**Issue by ph0llux** [sftpgo/sftpgo-plugin-auth#3]
sftpgo continuously asks the plugin for the auth information.
The transfers via WebDAV break down strongly, especially when transferring multiple files.
However, I'm not sure if this circumstance concerns the plugin or rather sftpgo itself...

**Comment by drakkan** [comment]
The support policy here is the same as for SFTPGo, please don't ask for free step by step support. Thanks for understanding
