### ISSUE TITLE
Login would fail if user password is changed in LDAP server.

### ISSUE THREAD

**Issue by ReeseWang** [sftpgo/sftpgo-plugin-auth#5]
Steps to reproduce

1. Login as a user at lease once. These logins should succeed.
2. Change the password of this user on the LDAP server.
3. Login again, both old and new password fail.

The new password fails because after a successful plugin authentication, `sftpgo` wouldn't update the user because the plugin returns an empty value, which is because user's group membership isn't changed. Then the new password is checked against the data provider, which contains old password hash, in `sftpgo/internal/dataprovider.isPasswordOK()`.

BTW the old password will succeed for a while if the LDAP server is Active Directory or Samba 4 because the old password is still usable for exactly one hour after changing.

**Comment by drakkan** [comment]
https://github.com/drakkan/sftpgo/commit/5ef0a2ed4b913f5d91b2d6367f3144ea76db5c22

**Comment by ReeseWang** [comment]
Wow that's a quick fix. Thanks
