### ISSUE TITLE
Installing on Windows

### ISSUE THREAD

**Issue by TineUser** [sftpgo/sftpgo-plugin-auth#7]
It's great to see that there's a Active Directory authentication plugin via LDAP :-). But how to install it on Windows with the provided exe file?

I only see opening a command line window but I can't see what's going on because this windows closes extremely fast. And it doesn't look like there's starting an installation. I already have SFTPgo 2.5.4 installed.

And where do I set the environment variables for this plugin? Or where do I configure this plugin with a config file?

**Comment by drakkan** [comment]
> It's great to see that there's a Active Directory authentication plugin via LDAP :-). But how to install it on Windows with the provided exe file?
> 

The file you download is the plugin executable, not an installer. Just use it

> I only see opening a command line window but I can't see what's going on because this windows closes extremely fast. And it doesn't look like there's starting an installation. I already have SFTPgo 2.5.4 installed.
> 
> And where do I set the environment variables for this plugin? Or where do I configure this plugin with a config file?

We no longer provide free step-by-step support, sorry. Please check our [support policy](https://github.com/drakkan/sftpgo#support-policy). Thanks for understanding

**Comment by TineUser** [comment]
Then you can stop with developing this software! As user we should get information about how to use the software and the add ons or plug ins. I didn't found a documentation so I don't know how to use it.
