### ISSUE TITLE
Unable to Login via SFTPgo After LDAP Password Change

### ISSUE THREAD

**Issue by pasqualemandato** [sftpgo/sftpgo-plugin-auth#9]
**Description:**
We have identified a specific issue with the SFTPgo system where users are unable to log in after changing their LDAP password. The following sequence of events outlines the problem:

1. A user successfully logged into the system, and his account was created successfully on SFTPgo
2. After a few months, the user decided to change his LDAP password.
3. Subsequent attempts to access SFTPgo using the updated LDAP password have failed.

**Expected Behavior:**
Users should be able to log in successfully to SFTPgo after changing their LDAP password.

**Actual Behavior:**
After changing the LDAP password, users are unable to log in to SFTPgo.

**Additional Information:**
- SFTPgo version: 2.5.4

**Comment by drakkan** [comment]
Hello, this is a support request and we don't provide free support, sorry
